[project]
name = "megadao"
requirements = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = [] # add ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[contracts.mega-dao]
path = "contracts/mega-dao.clar"
depends_on = ["proposal-trait", "extension-trait"]

# -- Extensions
[contracts.token]
path = "contracts/extensions/membership/token.clar"
depends_on = ["mega-dao", "sip010-ft-trait"]

[contracts.proposal-voting]
path = "contracts/extensions/voting/proposal-voting.clar"
depends_on = ["mega-dao", "proposal-trait", "extension-trait", "sip010-ft-trait", "token"]

[contracts.proposal-submission]
path = "contracts/extensions/proposal-submissions/proposal-submission.clar"
depends_on = ["mega-dao", "extension-trait", "proposal-voting"]

[contracts.emergency-proposals]
path = "contracts/extensions/executive-team/emergency-proposals.clar"
depends_on = ["mega-dao", "extension-trait", "proposal-voting"]

[contracts.emergency-execute]
path = "contracts/extensions/executive-team/emergency-execute.clar"
depends_on = ["mega-dao", "extension-trait"]

[contracts.vault]
path = "contracts/extensions/vaults/vault.clar"
depends_on = ["mega-dao", "extension-trait", "sip009-nft-trait", "sip010-ft-trait"]
# -- End of Extensions

# -- Bootstrap Proposals
[contracts.mdp-megadao]
path = "contracts/proposals/bootstraps/mdp-megadao.clar"
depends_on = ["mega-dao", "proposal-trait", "vault", "emergency-execute", "emergency-proposals", "proposal-submission", "proposal-voting", "token"]
# -- End of Bootstrap Proposals

# -- Transfer Proposals
[contracts.mdp-transfer-ft]
path = "contracts/proposals/transfers/mdp-transfer-ft.clar"
depends_on = ["proposal-trait", "vault"]

[contracts.mdp-transfer-stx]
path = "contracts/proposals/transfers/mdp-transfer-stx.clar"
depends_on = ["proposal-trait", "vault"]
# -- End of Transfer Proposals

# -- Traits
[contracts.extension-trait]
path = "contracts/traits/extension-trait.clar"
depends_on = []

[contracts.voting-trait]
path = "contracts/traits/voting-trait.clar"
depends_on = []

[contracts.proposal-trait]
path = "contracts/traits/proposal-trait.clar"
depends_on = []

[contracts.sip009-nft-trait]
path = "contracts/traits/sip009-nft-trait.clar"
depends_on = []

[contracts.sip010-ft-trait]
path = "contracts/traits/sip010-ft-trait.clar"
depends_on = []
# -- End of Traits

# -- External Contracts

# -- End of External Contracts