export const CONTRACTS = {
  megaDAO: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.mega-dao",
};

export const EXTENSIONS = {
  VAULT: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.mde-vault",
  SUBMISSION: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.mde-proposal-submission",
  VOTING: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.mde-snapshot-voting",
};

export const GOVERNANCE = {
  TOKEN: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.mega-token",
}

export const BOOTSTRAPS = {
  MULTISIG_DAO: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.sdp-multisignature-dao",
  DELEGATE_VOTING_DAO: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.sdp-delegate-voting-dao",
  NFT_DAO: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.sdp-nft-dao",
  VAULT: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.sdp-vault",
};

export const PROPOSALS = {
  SDP_TRANSFER_FUNGIBLE_TOKENS: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.mdp-transfer-ft",
};

// ERROR CODES

export enum MEGA_DAO_CODES {
  ERR_UNAUTHORIZED = 1000,
  ERR_ALREADY_EXECUTED = 1001,
  ERR_INVALID_EXTENSION = 1002,
};

export enum VAULT_CODES {
  ERR_UNAUTHORIZED = 3200,
  ERR_ASSET_NOT_WHITELISTED = 3201,
  ERR_FAILED_TO_TRANSFER_STX = 3202,
  ERR_FAILED_TO_TRANSFER_FT = 3203,
  ERR_FAILED_TO_TRANSFER_NFT = 3204,
};