export const CONTRACTS = {
  MEGA_DAO: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.mega-dao",
};

export const EXTENSIONS = {
  VAULT: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.vault",
  SUBMISSION: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.proposal-submission",
  VOTING: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.proposal-voting",
};

export const GOVERNANCE = {
  TOKEN: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.token",
}

export const BOOTSTRAPS = {
  MEGA_DAO: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.mdp-megadao",
};

export const PROPOSALS = {
  TRANSFER_TOKENS: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.mdp-transfer-ft",
  TRANSFER_STX: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.mdp-transfer-stx",
};

// ERROR CODES

export enum MEGA_DAO_CODES {
  ERR_UNAUTHORIZED = 1000,
  ERR_ALREADY_EXECUTED = 1001,
  ERR_INVALID_EXTENSION = 1002,
};

export enum SUBMISSION_CODES {
  ERR_UNAUTHORIZED = 2600,
  ERR_UNAUTHORIZED_PROPOSER = 2601,
  ERR_UNKNOWN_PARAMETER = 2602,
  ERR_PROPOSAL_MINIMUM_START_DELAY = 2603,
  ERR_PROPOSAL_MAXIMUM_START_DELAY = 2604,
};

export enum VOTING_CODES {
  ERR_UNAUTHORIZED = 2500,
  ERR_PROPOSAL_ALREADY_EXECUTED = 2501,
  ERR_PROPOSAL_ALREADY_EXISTS = 2502,
  ERR_UNKNOWN_PROPOSAL = 2503,
  ERR_PROPOSAL_ALREADY_CONCLUDED = 2504,
  ERR_PROPOSAL_INACTIVE = 2505,
  ERR_END_BLOCK_HEIGHT_NOT_REACHED = 2506,
  ERR_UNAUTHORIZED_VOTER = 2507,
  ERR_ALREADY_VOTED = 2508,
  ERR_UNKNOWN_PARAMETER = 2509,
  ERR_CANT_SELF_DELEGATE = 2510,
  ERR_NOTHING_TO_REVOKE = 2511,
  ERR_UNAUTHORIZED_DELEGATE = 2512,
}

export enum VAULT_CODES {
  ERR_UNAUTHORIZED = 3200,
  ERR_ASSET_NOT_WHITELISTED = 3201,
  ERR_FAILED_TO_TRANSFER_STX = 3202,
  ERR_FAILED_TO_TRANSFER_FT = 3203,
  ERR_FAILED_TO_TRANSFER_NFT = 3204,
};